name: Create release and publish package

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release go-std-utils linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64